### ISSUE TITLE
Codebase consolidation 

### ISSUE THREAD

**Issue by dzianisv** [cleverca22/toxvpn#6]
Hello, I started to develop toxcore based vpn as my diploma project 1.5 year ago. Firstly I had developed it as a part of libtoxcore on pure C, but a few months ago I decided to separate code from toxcore to a separate project called [toxvpn](https://gitlab.com/denis4net/toxvpn) on gitlab and migrated to use c++14. Then I find that you also started a similar project called also toxvpn. I think, it is good idea to consolidate our codebases to one project. But now I host my code on [gitlab](https://gitlab.com/denis4net/toxvpn) and use gitlabci mostly because gitlabci support a release artifacts storing "from the box". 

Used technologies and libraries:
- [linux capabilities](http://man7.org/linux/man-pages/man7/capabilities.7.html) allow run application witout root priviliges;
- [libnl](https://www.infradead.org/~tgr/libnl/) for network routes management;
- [tuntap](https://www.kernel.org/doc/Documentation/networking/tuntap.txt)

What do you think about it?

Regards, 
Denis

**Comment by cleverca22** [comment]
been busy lately with a different and larget toxcore project, havent been able to answer right away

i do have some more plans on features i want to toxvpn, but it may get swallowed up by the other project as an extra feature it has
